---

template_path: certificate.yaml

stack_tags:
   Purpose: website
   domain: {{ content_codename }}.assets.{{ root_domain }}
   role: serving

parameters:
   ContentCodename: {{ content_codename }}
   HostedZoneId: {{ hosted_zone_id }}
   RootDomain: {{ root_domain }}
