---

template_path: distribution.yaml

stack_tags:
   Purpose: assets:{{ content_codename }}:serving

parameters:
   CertificateArn: !stack_output images/certificate.yaml::CertificateArn
   CloudFrontPriceClass: PriceClass_100
   CloudFrontSecurityPolicy: TLSv1.2_2021
   ContentBucketDomainName: !stack_output images/hosting.yaml::BucketDomainName
   ContentCodename: {{ content_codename }}
   OriginAccessIdentity: !stack_output images/hosting.yaml::OriginAccessIdentity
   RootDomain: {{ root_domain }}
