---

template_path: dns.yaml

stack_tags:
   Purpose: website
   domain: {{ content_codename }}.assets.{{ root_domain }}
   role: serving

parameters:
   ContentCodename: {{ content_codename }}
   DistributionDomainName: !stack_output images/distribution.yaml::DistributionDomainName
   HostedZoneId: {{ hosted_zone_id }}
   RootDomain: {{ root_domain }}
