---

template_path: hosting.yaml

stack_tags:
   Purpose: website
   domain: {{ content_codename }}.assets.{{ root_domain }}
   role: hosting

parameters:
   AllowedOrigins:
      - https://www.djsp.de
      - https://www.djsp.es
      - https://www.djsp.eu
      - https://djsp.blog
      - https://blog.www.djsp.eu
      - https://flaschenpost.www.djsp.eu
