---

template_path: distribution.yaml

stack_tags:
   Purpose: website
   domain: {{ content_codename }}.assets.{{ root_domain }}
   role: serving

parameters:
   CertificateArn: !stack_output fonts/certificate.yaml::CertificateArn
   CloudFrontPriceClass: PriceClass_100
   CloudFrontSecurityPolicy: TLSv1.2_2021
   ContentBucketDomainName: !stack_output fonts/hosting.yaml::BucketDomainName
   ContentCodename: {{ content_codename }}
   OriginAccessIdentity: !stack_output fonts/hosting.yaml::OriginAccessIdentity
   RootDomain: {{ root_domain }}
