---


AWSTemplateFormatVersion: 2010-09-09


Description: CDN for assets


Parameters:

   CertificateArn:
      Description: ARN of the certificate.
      Type: String

   CloudFrontPriceClass:
      Description: Price class of CloudFront distribution.
      Type: String
      AllowedValues:
         - PriceClass_100
         - PriceClass_200
         - PriceClass_All

   CloudFrontSecurityPolicy:
      Description: Name of the CloudFront security policy to apply on HTTPS connections.
      Type: String
      AllowedValues:
         - TLSv1
         - TLSv1_2016
         - TLSv1.1_2016
         - TLSv1.2_2018
         - TLSv1.2_2019
         - TLSv1.2_2021

   ContentBucketDomainName:
      Description: Domain name of the S3 bucket hosting the content to be distributed.
      Type: String

   ContentCodename:
      Description: Codename for the type of content published with the distribution.
      Type: String

   OriginAccessIdentity:
      Description: ID of the origin access identity that is allowed to access the S3 bucket hosting the content to be distributed.
      Type: String

   RootDomain:
      Description: Root domain.
      Type: String
      AllowedPattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
      ConstraintDescription: must abide by domain name restrictions


Resources:

   Distribution:
      Type: AWS::CloudFront::Distribution
      Properties:
         DistributionConfig:
            Aliases:
               -
                  Fn::Sub: ${ContentCodename}.assets.${RootDomain}
            DefaultCacheBehavior:
               AllowedMethods:
                  - GET
                  - HEAD
                  - OPTIONS
               CachedMethods:
                  - GET
                  - HEAD
                  - OPTIONS
               CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
               Compress: true
               OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
               TargetOriginId: s3
               ViewerProtocolPolicy: redirect-to-https
            DefaultRootObject: ''
            Enabled: true
            HttpVersion: http2
            IPV6Enabled: true
            Origins:
               -
                  DomainName:
                     Ref: ContentBucketDomainName
                  Id: s3
                  S3OriginConfig:
                     OriginAccessIdentity:
                        Fn::Sub: origin-access-identity/cloudfront/${OriginAccessIdentity}
            PriceClass:
               Ref: CloudFrontPriceClass
            ViewerCertificate:
               AcmCertificateArn:
                  Ref: CertificateArn
               MinimumProtocolVersion:
                  Ref: CloudFrontSecurityPolicy
               SslSupportMethod: sni-only


Outputs:

   DistributionDomainName:
      Description: Domain name of the CloudFront distribution.
      Value:
         Fn::GetAtt:
            - Distribution
            - DomainName
